personalizacion_index:
    path:     /{genero}
    defaults: { _controller: PersonalizacionBundle:Default:index }

personalizacion_articulo:
    path:     /{genero}/{articulo}
    defaults: { _controller: PersonalizacionBundle:Default:articuloselect }