compra_homepage:
    path:     /
    defaults: { _controller: CompraBundle:Default:index }

compra_pendientes:
    path:     /pendientes/{personalizacionid}
    defaults: { _controller: CompraBundle:Default:pendientes }

compra_mastarde:
    path:     /mastarde/{personalizacionid}
    defaults: { _controller: CompraBundle:Default:mastarde }

compra_pedido:
    path:     /pedido/{id}/{precio}
    defaults: { _controller: CompraBundle:Default:pedido }