web:
    resource: "@WebBundle/Resources/config/routing.yml"
    prefix:   /

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario

articulo:
    resource: "@ArticuloBundle/Resources/config/routing.yml"
    prefix:   /

personalizacion:
    resource: "@PersonalizacionBundle/Resources/config/routing.yml"
    prefix:   /personalizacion

compra:
    resource: "@CompraBundle/Resources/config/routing.yml"
    prefix:   /compra

almacen:
    resource: "@AlmacenBundle/Resources/config/routing.yml"
    prefix:   /almacen

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /backend