usuario_iniciarsesion:
    path:     /iniciarsesion
    defaults: { _controller: UsuarioBundle:Default:iniciarsesion }

usuario_iniciarsesion_error:
    path:     /iniciarsesion/error
    defaults: { _controller: UsuarioBundle:Default:iniciarsesionerror }

usuario_registrarse:
    path:     /registro
    defaults: { _controller: UsuarioBundle:Default:registrarse }

usuario_cuenta:
    path:     /micuenta
    defaults: { _controller: UsuarioBundle:Default:cuenta }

usuario_cerrarsesion:
    path:     /cerrarsesion
    defaults: { _controller: UsuarioBundle:Default:cerrarsesion }