usuario_iniciarsesion:
    path:     /iniciarsesion
    defaults: { _controller: UsuarioBundle:Default:iniciarsesion }

usuario_registrarse:
    path:     /
    defaults: { _controller: UsuarioBundle:Default:registrarse }

usuario_cuenta:
    path:     /micuenta
    defaults: { _controller: UsuarioBundle:Default:cuenta }

usuario_cerrarsesion:
    path:     /cerrarsesion
    defaults: { _controller: UsuarioBundle:Default:cerrarsesion }