usuario_iniciarsesion:
    path:     /iniciarsesion
    defaults: { _controller: UsuarioBundle:Default:iniciarsesion }

usuario_registro:
    path:     /registro
    defaults: { _controller: UsuarioBundle:Default:registro }
