usuario_iniciarsesion:
    path:     /iniciarsesion
    defaults: { _controller: UsuarioBundle:Default:iniciarsesion }

usuario_iniciarsesion_error:
    path:     /iniciarsesion/error
    defaults: { _controller: UsuarioBundle:Default:iniciarsesionerror }

usuario_iniciarsesion_recordarpassword:
    path:     /iniciarsesion/password/recordar
    defaults: { _controller: UsuarioBundle:Default:recordarpassword }

usuario_iniciarsesion_password:
    path:     /iniciarsesion/password
    defaults: { _controller: UsuarioBundle:Default:passwordbien }

usuario_iniciarsesion_password_error:
    path:     /iniciarsesion/password/error
    defaults: { _controller: UsuarioBundle:Default:passworderror }

usuario_registrarse:
    path:     /registro
    defaults: { _controller: UsuarioBundle:Default:registrarse }

usuario_cuenta:
    path:     /micuenta
    defaults: { _controller: UsuarioBundle:Default:cuenta }

usuario_password:
    path:     /datospersonales/password
    defaults: { _controller: UsuarioBundle:Default:password }

usuario_direccion:
    path:     /datospersonales/direccion
    defaults: { _controller: UsuarioBundle:Default:direccion }

usuario_borrarcuenta:
    path:     /datospersonales/borrarcuenta
    defaults: { _controller: UsuarioBundle:Default:borrarcuenta }

usuario_pedidos:
    path:     /mispedidos/listado
    defaults: { _controller: UsuarioBundle:Default:pedidos }

usuario_pedidosrealizados:
    path:     /mispedidos/realizados
    defaults: { _controller: UsuarioBundle:Default:pedidosrealizados }

usuario_facturas:
    path:     /mispedidos/facturas/{numpedido}
    defaults: { _controller: UsuarioBundle:Default:facturas }

usuario_cerrarsesion:
    path:     /cerrarsesion
    defaults: { _controller: UsuarioBundle:Default:cerrarsesion }

