usuario_iniciarsesion:
    path:     /iniciarsesion
    defaults: { _controller: UsuarioBundle:Default:iniciarsesion }

usuario_registro:
    path:     /registro
    defaults: { _controller: UsuarioBundle:Default:registro }

usuario_cuenta:
    path:     /micuenta
    defaults: { _controller: UsuarioBundle:Default:cuenta }

usuario_cerrarsesion:
    path:     /cerrarsesion
    defaults: { _controller: UsuarioBundle:Default:cerrarsesion }