articulo_homepage:
    path:     /hello/
    defaults: { _controller: ArticuloBundle:Default:index }

busqueda:
    path:     /busqueda
    defaults: { _controller: ArticuloBundle:Default:busquedaindex }